import os
import subprocess
import sys
import json
from datetime import datetime
from transformers import GPT2LMHeadModel, GPT2Tokenizer
import random
import string
import time




def write_file(path, content):
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)




def generate_model_from_ai(prompt):
    try:
        tokenizer = GPT2Tokenizer.from_pretrained("distilgpt2")
        model = GPT2LMHeadModel.from_pretrained("distilgpt2")
        inputs = tokenizer(prompt, return_tensors="pt")
        outputs = model.generate(inputs["input_ids"], max_length=200)
        return tokenizer.decode(outputs[0], skip_special_tokens=True)
    except Exception as e:
        print(f"AI generation error: {e}")
        return ""




def create_folders(project):
    paths = [
        "app/api/routes", "app/models", "app/services", "tests"
    ]
    for path in paths:
        os.makedirs(os.path.join(project, path), exist_ok=True)




def create_static_files(project, db_user, db_password, db_name):
    try:
        write_file(os.path.join(project, ".env"), f"DATABASE_URL=postgresql://{db_user}:{db_password}@localhost:5432/{db_name}")
        write_file(os.path.join(project, "requirements.txt"), "\n".join([
            "fastapi", "uvicorn", "psycopg2-binary", "alembic", "sqlalchemy", "python-dotenv"
        ]))
        write_file(os.path.join(project, "README.md"), f"# {project}\n\nGenerated by Devin Agent 🧠")


        write_file(os.path.join(project, "app", "main.py"), """from fastapi import FastAPI
from app.api.routes import product


app = FastAPI()
app.include_router(product.router)


@app.get("/api/v1/")
def read_root():
    return {"message": "Welcome to your FastAPI app!"}
""")


        write_file(os.path.join(project, "app", "models", "product.py"), """from sqlalchemy import Column, Integer, String, Float
from app.database import Base


class Product(Base):
    __tablename__ = "products"
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, index=True)
    description = Column(String)
    price = Column(Float)
""")


        write_file(os.path.join(project, "app", "api", "routes", "product.py"), """from fastapi import APIRouter


router = APIRouter(prefix="/products", tags=["products"])


@router.get("/")
def get_products():
    return [{"id": 1, "name": "Sample Product"}]
""")


        write_file(os.path.join(project, "app", "database.py"), """from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
import os
from dotenv import load_dotenv


load_dotenv()
DATABASE_URL = os.getenv("DATABASE_URL")
engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()
""")


        for path in ["app/api/routes", "app/models"]:
            write_file(os.path.join(project, path, "__init__.py"), "")
    except Exception as e:
        print(f"Static file error: {e}")




def generate_password(length=16):
    return ''.join(random.choices(string.ascii_letters + string.digits, k=length))




def setup_postgresql():
    try:
        db_user = "postgres"
        db_password = generate_password()
        db_name = "mydb"
        container_name = "devin_pg"


        running = subprocess.check_output(["podman", "ps", "--format", "{{.Names}}"]).decode().splitlines()
        if container_name not in running:
            print("🛠️ Starting new PostgreSQL container...")
            subprocess.run([
                "podman", "run", "--name", container_name,
                "-e", f"POSTGRES_USER={db_user}",
                "-e", f"POSTGRES_PASSWORD={db_password}",
                "-e", f"POSTGRES_DB={db_name}",
                "-p", "5432:5432",
                "-d", "postgres"
            ], check=True)
            print("⏳ Waiting for PostgreSQL to start...")
            time.sleep(10)
        else:
            print("✅ PostgreSQL container already running.")


        return db_user, db_password, db_name
    except Exception as e:
        print(f"PostgreSQL setup error: {e}")
        return None, None, None




def setup_alembic(project, db_user, db_password, db_name):
    try:
        os.chdir(project)
        subprocess.run(["alembic", "init", "migrations"], check=True)


        with open("alembic.ini", "r", encoding="utf-8") as f:
            cfg = f.read()
        cfg = cfg.replace(
            "sqlalchemy.url = driver://user:pass@localhost/dbname",
            f"sqlalchemy.url = postgresql://{db_user}:{db_password}@localhost:5432/{db_name}"
        )
        with open("alembic.ini", "w", encoding="utf-8") as f:
            f.write(cfg)


        env_path = os.path.join("migrations", "env.py")
        with open(env_path, "r", encoding="utf-8") as f:
            env = f.read()
        env = env.replace(
            "target_metadata = None",
            "from app.database import Base\n"
            "target_metadata = Base.metadata"
        ).replace(
            "# add your model's MetaData object here",
            "from app.models import product  # Ensure models are imported"
        )
        with open(env_path, "w", encoding="utf-8") as f:
            f.write(env)


        subprocess.run(["alembic", "revision", "--autogenerate", "-m", "init"], check=True)
        subprocess.run(["alembic", "upgrade", "head"], check=True)
        os.chdir("..")
    except Exception as e:
        print(f"Alembic setup error: {e}")




def setup_venv(project):
    try:
        venv_path = os.path.join(project, "venv")
        print("🐍 Creating virtual environment...")
        subprocess.run([sys.executable, "-m", "venv", venv_path], check=True)


        pip = os.path.join(venv_path, "Scripts", "pip.exe") if os.name == "nt" else os.path.join(venv_path, "bin", "pip")
        subprocess.run([pip, "install", "-r", os.path.join(project, "requirements.txt")], check=True)
    except Exception as e:
        print(f"Virtualenv setup error: {e}")




def devin_agent():
    try:
        project = f"fastapi_project_{datetime.now().strftime('%Y%m%d%H%M%S')}"
        print(f"🚀 Creating: {project}")
        create_folders(project)


        db_user, db_password, db_name = setup_postgresql()
        create_static_files(project, db_user, db_password, db_name)
        setup_venv(project)


        if db_user and db_password and db_name:
            setup_alembic(project, db_user, db_password, db_name)


        print("🚀 Launching FastAPI app at http://0.0.0.0:8000 ...")
        uvicorn_exec = os.path.join(project, "venv", "Scripts", "uvicorn.exe") if os.name == "nt" else os.path.join(project, "venv", "bin", "uvicorn")
        subprocess.Popen([
            uvicorn_exec,
            "app.main:app",
            "--reload",
            "--host", "0.0.0.0",
            "--port", "8000"
        ], cwd=project)


        print(f"🎉 DONE: {project} is live at http://localhost:8000")
    except Exception as e:
        print(f"Agent error: {e}")




if __name__ == "__main__":
    devin_agent()




